import Head from "next/head"

import { type NextPageWithLayout } from "../_app"
import Tokens from "~/components/Coins/Tokens"
import WalletLayout from "~/components/layouts/wallet-layout"

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Wallet - BLOKC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/public/Mainlogo.PNG" />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/dg6o4qafx/image/upload/v1698131801/qmhrqtnzsvgmvoelwtle.png"
        />
        <meta name="theme-color" content="rgb(100,116,139)" />
      </Head>
      <>
        <div className="conatiner">
          <Tokens />
        </div>
      </>
    </>
  )
}

export default Page

Page.getLayout = function getLayout(page) {
  return <WalletLayout>{page}</WalletLayout>
}

//function TokenDataRow({
//  imageSrc,
//  name,
//  balance,
//}: {
//  imageSrc: string
//  name: string
//  balance: number
//}) {
//  return (
//    <>
//      <TableRow>
//      <TableCell className="w-[50px] pr-0">
//        <Image src={imageSrc} alt="Token logo" height="36" width="36" />
//      </TableCell>
//      <TableCell className="text-slate-600">{name}</TableCell>
//      <TableCell className="text-right text-slate-600">
//        ${balance.toFixed(6)}
//      </TableCell>
//    </TableRow>
//    </>
//  )
//}

{
  /* <div className="flex flex-1 flex-col">
        <div className="mt-10 flex justify-center space-x-10">
          <ActionButton label="Deposit" icon={<ArrowDown color="#fff" />} />
          <ActionButton label="Withdraw" icon={<ArrowUp color="#fff" />} />
        </div>

        <Card className="mx-7 mt-10 flex-1">
          <CardHeader className="pb-4">
            <CardTitle>
              <div className="flex items-center space-x-2 text-base text-slate-800">
                <CircleDollarSign className="h-6 w-6" />
                <span>Tokens</span>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent className="px-2">
            <Table>
              <TableBody>
                <TokenDataRow
                  imageSrc="https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png?1624446912"
                  balance={data?.maticBalance || 0}
                  name="MATIC"
                />
                <TokenDataRow
                  imageSrc="https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880"
                  balance={data?.wethBalance || 0}
                  name="WETH"
                />
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div> */
}
